### ISSUE TITLE
The problem when implementing the model on MAG Dataset

### ISSUE THREAD

**Issue by eddiegaoo** [facebookresearch/NARS#5]
When I try to run the model on the OGB-MAG dataset, I found that the cuda-related bug can not be fixed.

```
Using backend: pytorch
Namespace(R=5, batch_size=1, cpu_preprocess=False, data_dir=None, dataset='mag', dropout=0.5, eval_batch_size=50000, eval_every=10, ff_layer=2, gpu=0, input_dropout=False, lr=0.001, num_epochs=1000, num_hidden=512, seed=None, use_emb='TransE_mag', use_relation_subsets='sample_relation_subsets/examples/mag', weight_decay=0)
Traceback (most recent call last):
  File "train.py", line 139, in <module>
    main(args)
  File "train.py", line 45, in main
    data = load_data(device, args)
  File "/data/sgaoar/NARS/data.py", line 107, in load_data
    return load_mag(device, args)
  File "/data/sgaoar/NARS/data.py", line 170, in load_mag
    g.nodes["paper"].data["feat"] = torch.matmul(paper_feat, rand_weight.to(device))
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

 My setup is exactly the same as yours. And I checked the shape of "paper_feat" and "rand_weight.to(device)", and they are like [3xxxxx, 128] and [128,256]. So there is no mismatch in the dimension. And I check the GPU memory also when the data is being loaded, the GPU did not run out of memory. I don't know what results in this. Look forward to your reply!

**Comment by eddiegaoo** [comment]
After using the latest torch 1.9.1 cu111 to match the CUDA version of the server I used, the problem has been solved.

**Comment by lingfanyu** [comment]
Sorry for seeing the issue late. But it's cool that you've solved it!
